### ISSUE TITLE
Tried running the sample-app. It started but did not show any Patients or Organizations

### ISSUE THREAD

**Issue by richter122** [SAP-samples/openui5-fhir-sample-app#4]
After starting the app there was no data shown but I was able to access the resources via browser by clicking on the links: 
http://hapi.fhir.org/baseR4/Organization?_count=10&_format=json&_total=accurate

This may give a hint:
![image](https://user-images.githubusercontent.com/41431743/67082613-c215a700-f199-11e9-9971-73c1214ba91a.png)

Best regards

**Comment by KishoreKumarVivekanandan** [comment]
@richter122 I have checked the same, app is working fine. Could be a network issue at your end. Please check.

**Comment by flovogt** [comment]
Closed because of inactivity.
